// Package shim intercepts the native package manager on a bootc host.
//
// On an image-based system `dnf install` can't modify the read-only /usr and
// dies with a confusing error. The shims live in /usr/local/bin (machine-
// local, writable /var/usrlocal on bootc systems, ahead of /usr/bin in the
// default PATH), catch only the MUTATING subcommands, and redirect the user
// to remora — offering to run the equivalent `remora install/remove`
// interactively. Every other invocation (search, info, query, ...) is
// exec'd through to the real binary, so the tools stay useful.
//
// Scripts that call the absolute /usr/bin path are unaffected, and inside
// containers/toolboxes the container's own /usr/bin wins — the shims only
// ever apply to the host session, where the native command was already
// broken.
package shim

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Dir is where shims are installed.
const Dir = "/usr/local/bin"

// names returns the commands to shim for a package-manager family.
func names(pm string) []string {
	switch pm {
	case "dnf":
		return []string{"dnf", "dnf5", "yum"}
	case "zypper":
		return []string{"zypper"}
	case "pacman":
		return []string{"pacman"}
	case "apt":
		return []string{"apt", "apt-get"}
	case "portage":
		return []string{"emerge"}
	case "apk":
		return []string{"apk"}
	}
	return nil
}

// Script renders the shim for one command of a package-manager family.
func Script(pm, name string) (string, error) {
	var dispatch string
	switch pm {
	case "dnf", "zypper", "apt":
		// Subcommand-style tools. Map mutating subcommands to remora verbs.
		dispatch = `case "${1:-}" in
install|in) op=install ;;
remove|rm|erase|purge|autoremove) op=remove ;;
upgrade|update|dist-upgrade|dup) op=build ;;
*) op= ;;
esac`
	case "pacman":
		// Flag-style: -S… installs, -R… removes, -Syu upgrades.
		dispatch = `case "${1:-}" in
-S|-Sy) op=install ;;
-R|-Rs|-Rns|-Rdd) op=remove ;;
-Syu|-Su) op=build ;;
*) op= ;;
esac`
	case "portage":
		// emerge's default action installs; a bare atom means install,
		// explicit flags select remove/upgrade, other flags pass through
		// (--search, --pretend, --info, ...).
		dispatch = `case "${1:-}" in
--unmerge|-C|--depclean|-c) op=remove ;;
--sync|--update|-u|-uDN|-avuDN) op=build ;;
-*|"") op= ;;
*) op=install ;;
esac`
	case "apk":
		dispatch = `case "${1:-}" in
add) op=install ;;
del) op=remove ;;
upgrade) op=build ;;
*) op= ;;
esac`
	default:
		return "", fmt.Errorf("no shim for package manager %q", pm)
	}

	return fmt.Sprintf(`#!/bin/sh
# remora shim for %[1]s — generated by remora, remove with: remora shims --remove
# Mutating package operations can't touch the read-only /usr of a bootc
# system; they go through remora (local layering) instead. Everything else
# passes through to the real %[1]s.
real=""
for p in /usr/bin/%[1]s /usr/sbin/%[1]s /sbin/%[1]s /bin/%[1]s; do
    [ -x "$p" ] && { real="$p"; break; }
done
[ -n "$real" ] || { echo "remora shim: real %[1]s not found" >&2; exit 127; }

%[2]s

if [ -z "$op" ]; then
    exec "$real" "$@"
fi
shift

echo "This is a bootc (image-based) system: /usr is read-only, so '%[1]s' cannot change packages here." >&2
if [ "$op" = build ]; then
    echo "System updates are image updates. To rebuild your layered image on the newest base:" >&2
    echo "  remora build" >&2
else
    echo "Package changes are layered onto your image with remora:" >&2
    echo "  remora $op $*" >&2
fi
if [ -t 0 ] && [ -t 2 ]; then
    printf 'Run that now? [y/N] ' >&2
    read -r ans
    case "$ans" in
    y|Y|yes|YES) exec remora "$op" "$@" ;;
    esac
fi
exit 1
`, name, dispatch), nil
}

// Install writes the shims for pm into dir (Dir in production). It refuses
// to overwrite files it didn't generate.
func Install(dir, pm string) ([]string, error) {
	cmds := names(pm)
	if cmds == nil {
		return nil, fmt.Errorf("no shims defined for package manager %q", pm)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	var installed []string
	for _, name := range cmds {
		path := filepath.Join(dir, name)
		if data, err := os.ReadFile(path); err == nil && !isOurs(data) {
			return installed, fmt.Errorf("%s exists and is not a remora shim; not overwriting", path)
		}
		script, err := Script(pm, name)
		if err != nil {
			return installed, err
		}
		if err := os.WriteFile(path, []byte(script), 0o755); err != nil {
			return installed, err
		}
		installed = append(installed, path)
	}
	return installed, nil
}

// Remove deletes remora-generated shims for pm from dir. Files that aren't
// remora shims are left alone.
func Remove(dir, pm string) ([]string, error) {
	var removed []string
	for _, name := range names(pm) {
		path := filepath.Join(dir, name)
		data, err := os.ReadFile(path)
		if err != nil || !isOurs(data) {
			continue
		}
		if err := os.Remove(path); err != nil {
			return removed, err
		}
		removed = append(removed, path)
	}
	return removed, nil
}

func isOurs(data []byte) bool {
	return strings.Contains(string(data), "remora shim for")
}
