// Package factory materializes the local image factory: the build context
// under the state dir, the podman quadlet .build unit that rebuilds the
// image with Pull=newer, and the timer that makes it automatic. Pattern:
// renner0e/server / zerolayer / the Universal Blue "locally built,
// automatically updating custom bootc image" thread.
package factory

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/tuna-os/remora/internal/generate"
	"github.com/tuna-os/remora/internal/manifest"
)

const (
	// QuadletPath is the podman-systemd .build unit. Podman generates
	// remora-build.service from it at daemon-reload.
	QuadletPath = "/etc/containers/systemd/remora.build"
	// TimerPath schedules automatic rebuilds of remora-build.service.
	TimerPath = "/etc/systemd/system/remora-build.timer"
	// ServiceName is the quadlet-generated build service.
	ServiceName = "remora-build.service"
	// TimerName is the rebuild timer.
	TimerName = "remora-build.timer"
	// UupdDropinPath hooks the rebuild into uupd (Universal Blue's updater)
	// when it is present: uupd runs, remora rebuilds first, and uupd's bootc
	// step applies the fresh local image under uupd's own gating (battery,
	// metered network, inhibitors). Pure systemd — no dependency on uupd.
	UupdDropinPath = "/etc/systemd/system/uupd.service.d/10-remora.conf"
)

// WriteContext (re)generates the build context in dir: Containerfile plus
// the build_files/ and system_files/ skeletons if missing.
func WriteContext(dir string, m *manifest.Manifest, base, pmName string) error {
	cf, err := generate.Containerfile(m, base, pmName)
	if err != nil {
		return err
	}
	for _, sub := range []string{"build_files", "system_files"} {
		if err := os.MkdirAll(filepath.Join(dir, sub), 0o755); err != nil {
			return err
		}
	}
	keep := filepath.Join(dir, "system_files", ".gitkeep")
	if _, err := os.Stat(keep); os.IsNotExist(err) {
		_ = os.WriteFile(keep, nil, 0o644)
	}
	return os.WriteFile(filepath.Join(dir, "Containerfile"), []byte(cf), 0o644)
}

// Quadlet renders the .build unit for m building from dir. exe is the path
// to the remora binary the unit calls back into.
//
// Two details matter for correctness:
//
//   - PodmanArgs=--timestamp 0 normalizes layer timestamps, so a rebuild
//     whose inputs did not change produces a byte-identical image with the
//     same digest. That is what makes the no-op path in `remora apply` real
//     rather than theoretical.
//   - The rebase runs through `remora apply` rather than a literal
//     `bootc switch localhost/remora:latest`. Switching to a bare tag hands
//     bootc the same image specification on every run, so a rebuild that
//     produced new content under an unchanged tag may not get staged.
//     `remora apply` resolves the freshly built digest and switches to
//     tag@digest, and skips the switch entirely when the digest already
//     matches the staged or booted deployment.
func Quadlet(m *manifest.Manifest, dir, exe string) string {
	tag := m.ImageTag()
	return fmt.Sprintf(`# Generated by remora — DO NOT EDIT (regenerated by remora init/build).
# Rebuilds the local layered image on top of the newest base, then rebases.
[Build]
ImageTag=%s
Pull=newer
SetWorkingDirectory=%s
# Reproducible layer timestamps: identical inputs => identical digest.
PodmanArgs=--timestamp 0

[Service]
# Refresh the pinned base digest from the registry before building, so a new
# base published upstream is what we build on top of. Prefixed with "-": a
# registry that is unreachable must not block a rebuild of the existing pin.
ExecStartPre=-%s --dir %s upgrade --no-build
# Rebase to the freshly built image, but only if its digest actually changed.
ExecStartPost=%s --dir %s apply
# Drop bootc image generations older than a week.
ExecStartPost=/usr/bin/podman image prune --force --filter=label=containers.bootc=1 --filter=until=168h

[Install]
WantedBy=multi-user.target
`, tag, dir, exe, dir, exe, dir)
}

// Timer renders the rebuild timer for m.
func Timer(m *manifest.Manifest) string {
	return fmt.Sprintf(`# Generated by remora — DO NOT EDIT.
[Unit]
Description=Rebuild the remora layered image on schedule

[Timer]
OnCalendar=%s
# Missed while powered off? Run on next boot.
Persistent=true
# Spread load on package mirrors.
RandomizedDelaySec=15m

[Install]
WantedBy=timers.target
`, m.OnCalendar())
}

// UupdDropin renders the uupd hook: rebuild the local layer before uupd's
// update pass so its bootc step picks up the fresh image.
func UupdDropin() string {
	return `# Generated by remora — DO NOT EDIT.
# Rebuild the local layered image before uupd updates the system, so uupd's
# bootc step applies the freshly built image (with uupd's own gating and
# reboot/notification handling).
[Unit]
Wants=` + ServiceName + `
After=` + ServiceName + `
`
}

// InstallUupdHook writes the uupd drop-in under root (root == "/" for the
// real system; tests pass t.TempDir()).
func InstallUupdHook(root string) error {
	path := filepath.Join(root, UupdDropinPath)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(UupdDropin()), 0o644)
}

// InstallUnits writes the quadlet and timer under root (root == "/" for the
// real system; tests pass t.TempDir()) and reloads systemd.
func InstallUnits(m *manifest.Manifest, dir, root, exe string, reload func() error) error {
	quadletPath := filepath.Join(root, QuadletPath)
	timerPath := filepath.Join(root, TimerPath)
	if err := os.MkdirAll(filepath.Dir(quadletPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(quadletPath, []byte(Quadlet(m, dir, exe)), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(timerPath, []byte(Timer(m)), 0o644); err != nil {
		return err
	}
	return reload()
}
