// Package generate renders the build context remora maintains under its
// state dir: a Containerfile derived from the manifest, per package manager.
// The generated file is overwritten on every build — users customize via the
// manifest, build_files/ scripts, and system_files/ overlay, never by editing
// the Containerfile.
package generate

import (
	"fmt"
	"strings"

	"github.com/tuna-os/remora/internal/manifest"
)

// pm holds the per-package-manager fragments of the generated RUN script.
type pm struct {
	// cacheMounts are extra --mount flags on the RUN line (package caches).
	cacheMounts []string
	// install renders the package installation command.
	install func(pkgs []string) string
}

var pms = map[string]pm{
	"dnf": {
		cacheMounts: []string{
			"--mount=type=cache,dst=/var/cache/libdnf5",
			"--mount=type=cache,dst=/var/cache/dnf",
		},
		install: func(pkgs []string) string {
			return "dnf -y install \\\n    " + strings.Join(pkgs, " \\\n    ")
		},
	},
	"zypper": {
		cacheMounts: []string{"--mount=type=cache,dst=/var/cache/zypp"},
		install: func(pkgs []string) string {
			return "zypper --non-interactive install --no-recommends \\\n    " + strings.Join(pkgs, " \\\n    ")
		},
	},
	"pacman": {
		cacheMounts: []string{"--mount=type=cache,dst=/var/cache/pacman/pkg"},
		install: func(pkgs []string) string {
			return "pacman -Sy --noconfirm --needed \\\n    " + strings.Join(pkgs, " \\\n    ")
		},
	},
	"apt": {
		cacheMounts: []string{
			"--mount=type=cache,dst=/var/cache/apt",
			"--mount=type=cache,dst=/var/lib/apt/lists",
		},
		install: func(pkgs []string) string {
			return "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \\\n    " + strings.Join(pkgs, " \\\n    ")
		},
	},
	"portage": {
		// Distfiles + binpkgs survive across rebuilds; whether emerge
		// compiles or fetches binpkgs is the base image's binhost config.
		cacheMounts: []string{
			"--mount=type=cache,dst=/var/cache/distfiles",
			"--mount=type=cache,dst=/var/cache/binpkgs",
		},
		install: func(pkgs []string) string {
			return "emerge --verbose \\\n    " + strings.Join(pkgs, " \\\n    ")
		},
	},
	"apk": {
		cacheMounts: nil, // apk's fetch step is cheap; no cache dir by default
		install: func(pkgs []string) string {
			return "apk add --no-interactive \\\n    " + strings.Join(pkgs, " \\\n    ")
		},
	},
}

// SupportedPMs lists the package managers Containerfile generation handles.
func SupportedPMs() []string { return []string{"dnf", "zypper", "pacman", "apt", "portage", "apk"} }

// Containerfile renders the full Containerfile for m. base is the resolved
// base image ref (never empty — the caller resolves "follow booted image"),
// pmName the resolved package manager.
func Containerfile(m *manifest.Manifest, base, pmName string) (string, error) {
	p, ok := pms[pmName]
	if !ok {
		return "", fmt.Errorf("unsupported package manager %q (supported: %s)",
			pmName, strings.Join(SupportedPMs(), ", "))
	}

	var b strings.Builder
	b.WriteString("# Generated by remora — DO NOT EDIT.\n")
	b.WriteString("# Customize via remora.yaml, build_files/*.sh, and system_files/ instead.\n\n")

	// Build context stage: scripts + overlay referenced without ending up
	// as layers in the final image (renner0e/server pattern).
	b.WriteString("FROM scratch AS ctx\n")
	b.WriteString("COPY build_files /build_files\n")
	b.WriteString("COPY system_files /system_files\n\n")

	fmt.Fprintf(&b, "FROM %s\n\n", base)

	mounts := append([]string{
		"--mount=type=bind,from=ctx,source=/,target=/ctx",
		"--mount=type=tmpfs,dst=/tmp",
	}, p.cacheMounts...)
	fmt.Fprintf(&b, "RUN %s <<'REMORA_EOF'\n", strings.Join(mounts, " \\\n    "))
	b.WriteString("set -euo pipefail\n\n")

	b.WriteString("# System files overlay\n")
	b.WriteString("if [ -d /ctx/system_files ] && [ -n \"$(ls -A /ctx/system_files 2>/dev/null)\" ]; then\n")
	b.WriteString("    cp -avf /ctx/system_files/. /\n")
	b.WriteString("fi\n\n")

	if len(m.ExtraRun) > 0 {
		b.WriteString("# extra_run (manifest)\n")
		for _, line := range m.ExtraRun {
			b.WriteString(line + "\n")
		}
		b.WriteString("\n")
	}

	if len(m.Packages) > 0 {
		b.WriteString("# Packages (manifest)\n")
		b.WriteString(p.install(m.Packages) + "\n\n")
	}

	b.WriteString("# User build scripts, in lexical order\n")
	b.WriteString("for script in /ctx/build_files/*.sh; do\n")
	b.WriteString("    [ -e \"$script\" ] || continue\n")
	b.WriteString("    echo \"remora: running $script\"\n")
	b.WriteString("    bash \"$script\"\n")
	b.WriteString("done\n")
	b.WriteString("REMORA_EOF\n\n")

	b.WriteString("RUN bootc container lint\n")
	return b.String(), nil
}
